name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.PERSONAL_TOKEN }}'
    steps:
      - uses: actions/checkout@v2
      - name: 'Create version tag'
        id: 'main'
        uses: Klemensas/action-autotag@stable
        with:
          tag_prefix: 'v'

      - name: 'Create latest tag'
        if: ${{ contains(steps.main.outputs.tagname, 'v') }}
        uses: EndBug/latest-tag@latest
