on:
  # Run whenever a pull request is updated
  pull_request:
    branches:
      - main
jobs:
  syncpack:
    runs-on: ubuntu-latest
    name: syncpack
    steps:
      # Check out the branch so we can read/write its files
      - uses: actions/checkout@v3
      # Use Node.js as syncpack is written in that
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Build
        run: pnpm build

      - uses: JamieMason/syncpack-github-action@0.2.2
        with:
          package-manager: 'pnpm'
          syncpack-version: '8.3.9'
        env:
          # If any options are set to 'fix' then
          # env.GITHUB_TOKEN is needed to push to PRs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
